# AulaP13

 -  Método de Householder para construção de Matriz simétrica tridiagonal semelhante.
 -  Factorização QR para aproximação dos Valores Próprios.


***
### Definição:
Duas matrizes $A$ e $B$ são semalhantes se existir uma matriz invertível $P$ tal que: 
$$ B=P^{-1} A P$$

### Proposição:
Se duas matrizes $A$ e $B$ são semelhantes então têm os mesmos valores próprios.


### Definição (Matriz de Householder):

Dado $\mathbf{v}\in\mathbb{R}$ com $||\mathbf{v}||=1$ uma matriz de Householder é da forma:

$$P=I-2\mathbf{v}\mathbf{v}^T.$$

**Obs.:** As matrizes de Householder são simétricas e ortogonais 
$$P^{-1}=P^T=P$$

***
## Método de Householder

Dada uma matriz $A\in\mathcal{M}_{n\times n}$ simétrica, o método de Householder permite construir uma matriz $B$ simétrica e tridiagonal, a qual é semelhante à matriz $A$.

A matriz $B$ é construida recorrendo a $n-2$ matrizes de Householder.





***

#### Algoritmo 

Seja $A=[a^0_{i\,j}]=A_0 \in \mathcal{M}_{n\times n}.$

** Parte 1:** Determinação das matrizes de Householder $P_k$

1. Considerar os vectores $$\mathbf{v}^k=(0,\dots,0,v^k_{k+1},\dots,v^k_{n})$$
onde 

 -  a)
$$v^k_{k+1}=\left(\frac{1}{2}+\frac{|a^{k-1}_{k+1\, k}|}{2 S_k}\right)^{1/2}$$

 -  b)
$$ v^k_{j}=\frac{a^{k-1}_{j\, k} sgn(a^{k-1}_{k+1\, k})}{2v^k_{k+1}S_k},\quad j=k+2,\dots,n $$

 -  c) 

$$ S_k=\sqrt{(a^{k-1}_{k+1\, k})^2+\dots+ (a^{k-1}_{n\, k})^2}=\sum_{i=k+1}^n (a^{k-1}_{i,k})^2$$

   -  d) 
$$P_k=I-2\mathbf{v}^k{\mathbf{v}^k}^T$$

**Parte 2:** Determinação da matriz $B$.


1. para $k$ entre $1$ e $n-2$

    $$A_k=P_k A_{k-1} P_k$$
    
2.   $B=P_{n-2}A_{n-3}P_{n-2}=A_{n-2}$

***
### Uma implementação do  Algoritmo do método de Householder

In [2]:
import numpy as np

class Householder:
    def __init__(self, A):
        self.A = A
        self.dim=len(A)
        
                
    def Tridiag(self):
        n=self.dim
        B=np.array(self.A) 
        
        Id=np.identity(n)
        for k in range(0,n-2):
            P=np.zeros((n,n))
            v=np.zeros(n)
            
            S=np.sum(B[k+1:,k]**2)**0.5
            
            v[k+1]=(0.5+np.abs(B[k+1,k])/(2*S))**0.5
            v[k+2:]=B[k+2:,k]*np.sign(B[k+1,k]) /(2*S*v[k+1])
            
            P=Id-2.0*np.outer(v,v.transpose()) # vector Nx1 por vector 1xN (produto externo)
            
            B=P.dot(B).dot(P) # PxBxP
            
            
        return B  

### Exercícios:

Utilize a classe implementada para diagonalizar as matrizes seguintes:

$A_1=\left[\begin{array}{*{4}c}
4.0 & 1.0 & -2.0 & 2.0 \\
1.0 & 2.0 & 0.0 & 1.0 \\
-2.0 & 0.0 & 3.0 & -2.0 \\
2.0 & 1.0 & -2.0 & -1.0 \\
\end{array}\right]$

$A_2=\left[\begin{array}{*{5}c}
8.0 & 0.25 & 0.5 & 2.0 & -1.0 \\
0.25 & -4.0 & 0.0 & 1.0 & 2.0 \\
0.5 & 0.0 & 5.0 & 0.75 & -1.0 \\
2.0 & 1.0 & 0.75 & 5.0 & -0.5 \\
-1.0 & 2.0 & -1.0 & -0.5 & 6.0 \\
\end{array}\right]$


In [5]:
# Sandbox
A2=np.array([[8.0 , 0.25 , 0.5 , 2.0 , -1.0], 
            [0.25 , -4.0 , 0.0 , 1.0 , 2.0],
            [0.5 , 0.0 , 5.0 , 0.75 , -1.0], 
            [2.0 , 1.0 , 0.75 , 5.0 , -0.5], 
            [-1.0 , 2.0 , -1.0 ,-0.5 , 6.0]])
np.set_printoptions(5,suppress=True)
B=Householder(A2).Tridiag()
print(B)
#print(np.linalg.eig(A2)[0]-np.linalg.eig(B)[0])

[[ 8.      -2.30489 -0.      -0.       0.     ]
 [-2.30489  5.92941  1.50226  0.      -0.     ]
 [-0.       1.50226  1.7715  -4.89015  0.     ]
 [-0.       0.      -4.89015 -0.43612 -1.08989]
 [ 0.       0.      -0.      -1.08989  4.73521]]


***
## O algoritmo $QR$ para calcular os valores próprios de uma matrizes simétricas e tridiagonais


**Objectivo:** Aproximar os valores próprios de uma matriz tridiagonal simétrica $B_0$.  

**Ideia:** Construir uma sucessão de Matrizes $B_n=Q^{(n)}R^{(n)}\, (n>0)$ que tende para uma matriz diagonal e tais que são semelhantes à matriz simétrica tridiagonal $B_0$.

**Observação:** Se $B_0$ resultar do método de Householder, então é semelhante à matriz $A$ e portanto a  matriz "aproximadamente" diagonal resultante do processo de factorização QR é também semelhante à matriz $A$.
 




### Factorização $Q R$ de matrizes simétricas tridiagonais por meio das matrizes de rotação.

- $Q$ matriz ortogonal.
- $R$ matriz triangular superior.

Dada $B_j$ matriz tridiagonal simétrica podemos factorizar na forma pretendida da forma seguinte:

$$B_j=\underbrace{(C_2^T\cdots C_n^T)}_{Q_j}\, \underbrace{(C_n\cdots C_2  B_j)}_{R_j}$$

Onde $C_k$ é uma matriz (ortogonal) de rotação.:

$$
C_k=C_k(\theta)=\begin{bmatrix}
1& 0&  \cdots &\cdots&\cdots&0\\
0& \ddots& 0& \cdots &\cdots&\vdots\\
\vdots&0&\cos(\theta) &\sin(\theta)&0& \vdots \\
\vdots&0&-\sin(\theta) &\cos(\theta)& 0&\vdots \\
\vdots&\cdots&\cdots &\cdots&1 &\vdots \\
0&\cdots& \cdots&\cdots &\cdots& \ddots\\
\end{bmatrix}
$$

Os ângulos $\theta$ são calculados de forma a anular (progressivamente) os termos da diagonal inferior da matriz $B_j$.

A matriz semelhante $B_{j+1}$ será então calculada fazendo $$B_{j+1}=R_j Q_j\quad (= Q^{-1}_j B_j Q_j) $$

### Uma implementação do método QR 

In [6]:
import numpy as np

class QR:
    def __init__(self,B0,MaxIter):
        self.B0=B0
        self.dim=len(B0)
        self.MaxIter=MaxIter
        
    def Diagonalize(self):
        n=self.dim
        B=np.array(self.B0)
        
        for i in range(0,self.MaxIter):
            R=np.array(B)
            Q=np.identity(n)
            
            for k in range(0,n-1):
                C=np.identity(n)
                theta=np.arctan(R[k+1,k]/R[k,k])
                
                C[k,k]=np.cos(theta)
                C[k,k+1]=np.sin(theta)
                C[k+1,k]=-C[k,k+1]
                C[k+1,k+1]=C[k,k]
               
                R=C.dot(R)
                Q=Q.dot(C.transpose())
                
            B=R.dot(Q)
        
        return B         

***

In [14]:
#Sandbox (ver aula Teórica)
A=np.array([[4.,-5.0**0.5,0],
            [-5.0**0.5,11./5.,-8./5.],
            [0,-8./5.,24./5.]])

In [23]:
B=QR(A,50).Diagonalize()

In [24]:
print(B)

[[ 6.23073 -0.      -0.     ]
 [-0.       4.48286 -0.     ]
 [ 0.       0.       0.28642]]


***

### Exercício:
Aplique os algoritmos implementados para aproximar os valores próprios da matriz:


$$A_3=\begin{bmatrix}
2 & -1 & -1 & 0 &0\\
-1 & 3 & 0 & -2 &0\\
-1 & 0 & 4 & 2 &1\\
0 & -2 & 2 & 8 &3\\
0 & 0 & 1 & 3 &9
\end{bmatrix}
$$

In [88]:
A=np.array([[2, -1, -1 , 0 ,0],
            [-1 , 3 , 0 , -2 ,0],
            [-1 , 0 , 4 , 2 ,1],
            [0 , -2 , 2 , 8 ,3],
            [0, 0 , 1 , 3 ,9]])

Atr=Householder(A).Tridiag()
B=QR(Atr,50).Diagonalize()
print(B)

[[ 12.26321   0.        0.        0.       -0.     ]
 [  0.        6.26491   0.        0.        0.     ]
 [ -0.        0.        4.36338  -0.        0.     ]
 [ -0.       -0.        0.        2.05127   0.     ]
 [ -0.       -0.       -0.        0.        1.05723]]


In [ ]:
# verificação
print(np.linalg.eig(A)[0])

### Exercício:

Implemente uma condição de paragem no método de factorização $QR$ que dependa de uma tolerância para o erro  entre duas iterações consecutivas.   