# AulaP9

- Exercícios sobre Fórmulas de Quadratura Fechadas (Newton-Cotes)
- Métodos Directos para resolução de Sistemas Lineares

***

### Algumas Fórmulas de Newton-Cotes Compostas com Erro

**Notações**: Pontos igualmente espaçados $$h=x_{i+1}-x_i=\frac{x_n-x_0}{n}\quad \text{e}\quad f_i=f(x_i)\quad, (i=,1\dots, n):$$

1. Regra dos Trapézios: 
$$\int_{x_0}^{x_n} f(x)\, {\rm d}x = \frac{h}{2}(f_0+2\sum_{i=1}^{n-1}f_i+f_n)-\frac{h^2(x_n-x_0)}{12}f''(\xi),\quad \xi\in[x_0,x_n]$$

- Regra de **Simpson** (n par):   
$$\int_{x_0}^{x_n}f(x)\, {\rm d}x=\frac{h}{3}\left(f_0+2\sum_{i=1}^{(n/2)-1}f_{2i}+4\sum_{i=1}^{(n/2)}f_{2i-1} + f_n\right)-\frac{h^4(x_n-x_0)}{180}f^{(IV)}(\xi),\quad \xi\in[x_0,x_{n}]$$


***

### Exercício:
- Considere $\displaystyle I=\int_{0}^{6}\frac{1}{1+x^2}\, {\rm d}x$.

 1. Calcule o valor exacto de $I$.
 - Utilize uma  regra de Newton-Cotes simples para aproximar o valor
  de $I$ dividindo o intervalo $[0,6]$ em $6$ sub-intervalos com a mesma
  amplitude.
 - Considere a partição do intervalo de integração $[a,b]$ da alínea
  anterior e  utilize a regra dos trapézios composta  para aproximar o valor de $I$.
 - Calcule os erros (exactos) obtidos nas alíneas b) e c) e
  comente. 

In [ ]:
# 2.
from math import atan
Iex=atan(6)
print(Iex)

import numpy as np
x=np.linspace(0,6,7)
f=1/(1+x**2)
h=1

Iweddel=h/140.*(41*f[0]+216*f[1]+27*f[2]+272*f[3]+27*f[4]+216*f[5]+41*f[6])

print(Iweddel)

Itrap=h/2.*(f[0]+2*f[1]+2*f[2]+2*f[3]+2*f[4]+2*f[5]+f[6])

print(Itrap)


In [ ]:
# 4.
from scipy import interpolate
import matplotlib.pyplot as plt
import numpy as np

f= lambda x: (1/(1+x**2))

x = np.linspace(0, 6,1000)
plt.figure(figsize=(10, 8))
plt.plot(x,f(x),lw=2.0,label='$f(x)$')

xs=[0,1,2,3,4,5,6]
ys=[f(0),f(1),f(2),f(3),f(4),f(5),f(6)]

# Polinómio interpolador de grau 6 (6 sub-intervalos; 7 pontos)
p6f = interpolate.lagrange(xs, ys)
xp6 = np.arange(0,6, 0.01)
yp6 = p6f(xp6)

plt.plot(xs,ys, color='k', label='Trap.')
plt.plot(xp6,yp6, color='brown', label='Weddel')

#fill_between(xs,ys,0,color='grey')
#text(1.2,1.0,'$t_0$', fontsize=14)

plt.xlabel(r'$\mathrm{eixo-} x_i\, x_0=0,\dots,x_6=6,\,h=1$')
plt.ylabel(r'$\mathrm{eixo-} y=f(x)$')
#plt.ylim(0.0,1.1)
plt.ylim(0.0,0.07)
plt.xlim(4.0,6.0)
plt.legend(loc='best')
plt.show()
plt.clf()

***

### Exercício
 
 - Pretende-se calcular $\displaystyle \ln 2=\int_1^2\frac{1}{x}\, {\rm d}x$.
 
Qual o número de sub-intervalos a considerar de  forma a que a regra de
Simpson composta conduza a valor aproximado de $\ln 2$ com erro de
truncatura inferior ou igual a $0.5\times 10^{-3}$.


***

# Métodos Directos para resolver $Ax=b$

  Considere-se um
  sistema escrito na forma matricial,

 Conhecem-se os seguintes resultados:

- $Ax=b$ tem solução única se $|A|\neq 0$ ou de forma equivalente
    quando $R(A|b)=R(A)=n$ e neste caso diz-se **não singular**.


- $Ax=b$ tem soluções múltiplas quando $R(A)=R(A|b)<n$ e neste caso
    diz-se singular.


- $Ax=b$ não tem solução quando $R(A|b)>R(A)$ e neste caso diz-se
    singular.
 

### Só iremos estudar métodos para resolver o caso não singular.

 - No caso não singular sabe-se que $Ax=b\Leftrightarrow x=A^{-1}b$. 

- Note-se que quando se
  trata um sistema com dimensão elevada o processo de inversão da matriz é muito
  dispendioso numericamente.

 
 - Pelo mesmo motivo o uso da regra de Cramer (cálculo de determinantes) também não é praticável.  

### Problemas na resolução de sistemas lineares.
  
  Em geral diz-se que
  um sistema está Mal acondicionado quando:
  
 - Um sistema não singular se transforma num singular em função dos erros de
    arredondamento.
 
 
 - Pequenas perturbações nos coeficientes do sistema produzem grandes
    alterações nas soluções.  (Exemplo: Um arredondamento pode produzir uma grande
    alteração na solução.)
  

 - O *mau-acondicionamento* de um sistema pode ser medido através da relação entre o determinante de $A$ e os seus coeficientes.
  Em geral também se verifica um *mau-acondicionamento* do sistema quando nele se
    encontram coeficientes com ordem de grandeza muito diferentes.
  

## Métodos Directos
  
  Os métodos directos de resolução de sistemas
  caracterizam-se essencialmente pelo facto de produzirem soluções exactas no caso
  de não existirem erros de arredondamento.

### Método de eliminação de Gauss (...O que utilizamos habitualmente à mão...)

  Este método consiste na resolução de $Ax=b$ por meio da substituição descendente
  e ascendente.
  $$Ax=b\Leftrightarrow Ux=b_U\Leftrightarrow Ix=b_I$$ onde $U$ é uma matriz
  triangular superior e $I$ é a matriz identidade.


### Eliminação de Gauss com Pesquisa Parcial de Pivot 

  Este método consiste na Eliminação de Gauss com troca prévia de linhas de forma
  a que o Pivot seja o coeficiente da coluna em causa com maior valor absoluto.
  
  - Este processo não resulta bem quando a matriz é desequilibrada, isto é, quando
    os elementos da matriz tem grandezas muito distintas.
  

  **Eliminação de Gauss com Pesquisa Total de Pivot**
  
  Este processo é análogo ao
  anterior mas admite troca de colunas no sistema, de forma a escolher o Pivot de
  maior valor absoluto.
 
 - É necessário, no caso em que há troca de colunas proceder também à troca da ordem das incógnitas.


***

**DEFINIÇÃO:** Uma matriz $A\in {\cal M}_{n\times n}$ admite factorização se existirem $M_i$
com $i\in\{1,\cdots,k\}$ tais que $A=M_1\cdots M_k$.

***

**No caso em que não há troca de linhas**, o método de Gauss (redução à forma de escada) fornece uma **factorização** da forma 
<br>

$$A=LU\quad (A=a_{ij}=a^1_{ij}):$$
<br>
    
$$
       \begin{bmatrix}
        1&0&\cdots&\cdots&0\\ m_{21}&1&\cdots&\cdots&0\\ m_{31}&m_{32}&1&\cdots&0\\ \vdots&\vdots&\vdots&\vdots&\vdots
      \end{bmatrix}
      \begin{bmatrix}
        a^1_{11}&a^1_{12}&\cdots&\cdots&a^1_{1N}\\ 0&a^2_{22}&\cdots&\cdots&a^2_{2N}\\ 0&0&a^3_{33}&\cdots&a^3_{3N}\\ \vdots&\vdots&\vdots&\vdots&\vdots
      \end{bmatrix}
$$

Os coeficientes das matrizes e vector independente $b$ $(Ax=b\Leftrightarrow L\, Ux=b)$ são dados por:
    
$$m_{ik}=\frac{a^k_{ik}}{a^k_{kk}},\,i=k+1\cdots N\quad({\tt Coluna\, de\, L})$$
    
$$a^{k+1}_{ij}=a^{k}_{ij}-m_{ik}a^k_{kj},\, i,j=k+1,\cdots,N \quad ({\tt Linha\,
      e\, colunas\, de\, U})$$
    
$$b^{k+1}_{i}=b^{k}_{i}-m_{ik}b^k_{k},\quad i=k+1,\cdots,N $$


***

## Método Factorização de Crout


 **PROPOSIÇÃO:** <br>

- A menos de trocas de linhas, uma matriz $A$ invertível admite factorização na
 forma $LU$, onde $L$ é uma matriz triangular inferior e $U$ uma matriz
 triangular superior onde todos os elementos da diagonal são 1.
 
 
 **Nota:** Sabe-se que $|A|=|L|\times |U|$, donde se conclui que $U$ e $L$ são invertiveis.

***
 

**PROPOSIÇÃO:**<br>   

-  Uma matriz $A$ invertível admite uma factorização do tipo: $$P^{-1}A=LU$$ onde
    $P$ é uma matriz de permutação.
    
    
-  Se os *menores principais* de $A$ forem todos não nulos então $A$ admite uma
    factorização do tipo $$A=LU,$$ isto é, na proposição anterior $P=I$.
 ***

Tem-se então o método seguinte:

$$Ax=b\Leftrightarrow LUx=b\Leftrightarrow Ly=b\wedge Ux=y$$

Portanto resolve-se
$Ly=b$ (*Descida*) e de seguida $Ux=y$ (*Subida*).

***
  ### Factorização LU
  
  O algoritmo que  permite o cálculo de $L$ e $U$ é  o seguinte:
  - Para $k=1,\dots,n$
  $$l_{ik}=a_{ik}-\sum_{r=1}^{k-1}l_{ir}u_{rk}\quad i=k,\dots,n $$
  $$u_{kj}=(a_{kj}-\sum_{r=1}^{k-1}l_{kr}u_{rj})/l_{kk}\quad j=k+1,\dots,n$$
  
  - Calcula-se uma coluna de $L$ seguida pela linha de $U$.
  

***
### Processos de descida ($Ly=b$)  e subida ($Ux=y$) para resolução do sistema após factorização:


$$y_1=\frac{b_1}{l_{11}},\quad y_i=\frac{1}{l_{ii}}\left(b_i-\sum_{j=1}^{i-1}l_{ij}y_j\right),\quad i=2,\dots,n$$

$$x_n=\frac{y_n}{u_{nn}},\quad x_i=\frac{1}{u_{ii}}\left(y_i-\sum_{j=i+1}^{n}u_{ij}x_j\right),\quad i=2,\dots,n$$
***

### **Notas:**

- Para poupar memória, ao programar o método, é usual guardar as matrizes $L$ e
    $U$ numa só matriz fazendo $M=L+U-I.$
    
  
- Se ao longo do processo se tiver $l_{kk}=0$ então é necessário proceder à troca
  de linhas na matriz $A$ inicial.
  
  

  
- O número de operações para factorizar $A$ na forma $LU$ é da ordem de $O(n^3)$
  no entanto para resolver os dois sistemas associados são necessárias $O(n^2)$
  operações. Este método apresenta ganhos quando é necessária a resolução de
  vários sistemas com a mesma matriz $A$.  
  Usando $Gauss$ tem-se sempre $O(n^3)$
  operações.
  

***

### Uma implementação do método de Crout

In [1]:
import numpy as np

class Crout:
    def __init__(self,A,b):
        self.dim=len(b)
        self.A=A
        self.b=b
        self.L=np.zeros((self.dim,self.dim))
        self.U=np.zeros((self.dim,self.dim))
        self.L, self.U = self.FactLU()
        self.y=np.zeros(self.dim)
        self.y=self.SolveDownLyb()
        self.x=np.zeros(self.dim)
        self.x=self.SolveUpUxy()
        
    def FactLU(self):
        A=self.A
        L=np.zeros((self.dim,self.dim))
        U=np.zeros((self.dim,self.dim))
        for i in range(0,self.dim): 
            U[i,i]=1.0
            
        for k in range(0,self.dim):
            # Column of L (M)
            for i in range(k,self.dim):
                L[i,k]=A[i,k]-np.inner(L[i,0:k],U[0:k,k])
            # Line of U (M)    
            for j in range(k+1,self.dim):
                assert L[k,k]!=0.0, 'Row permutation is required'
                U[k,j]=(A[k,j]-np.inner(L[k,0:k],U[0:k,j]))/L[k,k]
            
        return L, U #return the matrix M
        
    
    def SolveDownLyb(self): 
        y=np.zeros(self.dim)
        for i in range(0,self.dim):
            y[i]=(self.b[i]-np.sum(self.L[i,0:i]*y[0:i]))/self.L[i,i]
        
        return y #return the array y
    
    def SolveUpUxy(self):
        x=np.zeros(self.dim)
        for i in range(self.dim-1,-1,-1):
            x[i]=(self.y[i]-np.sum(self.U[i,i+1:self.dim]*x[i+1:self.dim]))
        
        return x #return the solution array x
    
        

## Exercício: 
- Teste a implementação da classe anterior com o sistema $Ax=b$ definido por:


$$
 \begin{bmatrix}
1&-1&2&-1\\
1&1&1&0\\
2 &-2&3&-3\\
1&-1&4& 3
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2\\
x_3\\
x_4
\end{bmatrix}=
\begin{bmatrix}
-8\\
-2\\
-20\\
4
\end{bmatrix}
$$

** Resolução **

In [13]:
A=np.array([[1.0,-1.0,2.0,-1.0],[1.0,1.0,1.0,0.0],
            [2.0,-2.0,3.0,-3.0],[1.0,-1.0,4.0,3.0]])

b=np.array([-8.0,-2.0,-20.0,4.0])

#A=np.array([[1.0,2.0,3.0],[-1.0,2.0,1.0],[-1.0,3.0,1.0]])

#b=np.array([1.0,2.0,1.0])

In [14]:
C=Crout(A,b)

In [15]:
from pprint import pprint
pprint(C.L)
print('\n')
pprint(C.U)
print('\n')

pprint(np.array_equal(A,np.dot(C.L,C.U)))
print('\n')

pprint(C.x)
print(np.array_equal(C.b,np.dot(A,C.x)))
print('\n')

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  2.,  0.,  0.],
       [ 2.,  0., -1.,  0.],
       [ 1.,  0.,  2.,  2.]])


array([[ 1. , -1. ,  2. , -1. ],
       [ 0. ,  1. , -0.5,  0.5],
       [ 0. ,  0. ,  1. ,  1. ],
       [ 0. ,  0. ,  0. ,  1. ]])


True


array([-7.,  3.,  2.,  2.])
True




***

## Método de Cholesky

 Se $A$ é uma matriz simétrica definida positiva, então $A$ admite uma
 factorização do tipo: 
 
 $$A=LL^T$$ onde $L$ é uma matriz triangular inferior.
  
 Relembrem-se as seguintes definições.
    
  - $A$ é simétrica se $A=A^T$.
  
  
  - $A$ é definida positiva se $X^T A X>0,\ \forall X\in \mathbb{R}^n, X\neq 0$.  
  
**Proposição** $A$ é definida positiva se os 
determinantes dos menores principais de $A$ forem todos positivos.
 
 $$
 |a_{11}|>0,\quad 
\left| \begin{matrix} a_{11} & a_{12}\\
 a_{21} & a_{22}
 \end{matrix}\right|>0, \quad \cdots |A|>0.
 $$

***
  A resolução do sistema $Ax=b$ resulta da mesma forma que o método de Crout:
  $$AX=b\Leftrightarrow LY=b \wedge L^TX=Y.$$ 
  
  
  O cálculo de $L$ é feito tendo em
  conta as seguintes fórmulas: $k=0,\dots,n$
  
  
 \begin{align*}\displaystyle l_{kk}&=\sqrt{a_{kk}-\sum_{r=1}^{k-1} l^2_{kr}}
 \\
 \\
  l_{ik}&=\frac{a_{ik}-\sum_{r=1}^{k-1}l_{ir}l_{kr}}{l_{kk}} \quad i=k+1,\dots,n
  \end{align*}
  e fazendo o cálculo por colunas. (Da primeira para a última.)



Este método apresenta uma melhoria no número de operações necessárias, quando
comparado com o método de Crout-- $O(n^3/6)$.

Neste caso nunca há o risco de acontecer que algum dos elementos da diagonal de
$L$ seja nulo. 

Se assim fosse viria $|A|=|L|^2=0$, tendo em conta que
$|L|=|L^T|$ que se pode calcular considerando a multiplicação dos elementos da
 diagonal de $L$.



***

### Exercícios:

- Determine as factorizações de Crout ($LU$) e de Cholesky ($LL^t$) das matrizes simétricas definidas positivas seguintes:

$$A_0=\begin{bmatrix}
4&-1&1\\
-1&4.25&2.75\\
1 &2.75&3.5
\end{bmatrix}
$$

$$A_1=\begin{bmatrix}
4&0&2&1\\
0&3&-1&1\\
2 &-1&6&3\\
1 & 1 & 3 &8
\end{bmatrix}
$$



 - Utilizando uma factorização da Forma $LL^t$, resolva o sistema linear seguinte:
 $$
 \begin{bmatrix}
4&1&1&1\\
1&3&0&-1\\
1 & 0&2&1\\
1&-1&1& 4
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2\\
x_3\\
x_4
\end{bmatrix}=
\begin{bmatrix}
3\\
2\\
1\\
1
\end{bmatrix}
$$